import type { Metadata } from "next";

import "./globals.css";

import NavbarServer from "@/components/NavbarServer";

export const metadata: Metadata = {
  title: "Search-Transcripts-Archive",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* <Navbar></Navbar> */}
        <NavbarServer></NavbarServer>
        {children}
      </body>
    </html>
  );
}
